version: "3.9"
services:
  kittycash-assistant:
    build: .
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: >
      bash -c "
      python -m scripts.build_index &&
      python -m src.app --mode api --host 0.0.0.0 --port 8000
      "
