# © 2025 Kittycash Team. All rights reserved to Trustnet Systems LLP.
version: "3.7"

volumes:
  data:
  model_cache:
  ollama_data:

services:

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=llama3:latest

    networks:
      - kittycash_cool_network

  data_indexing_service:
    build:
      context: ./data_indexing_service
    container_name: kittycash_data_indexing
    ports:
      - "9003:9003"
    volumes:
      - ./data:/data
      - model_cache:/root/.cache
    environment:
      - EMBED_MODEL=imagebind
      - INDEX_DIR=/data/faiss_index
      - KB_PATH=/data/knowledge_base.txt
      - DOCSTORE_PATH=/data/docstore.json
      - IN_DOCKER=true
    networks:
      - kittycash_cool_network

  retrieval_service:
    build:
      context: ./retrieval_service
    container_name: kittycash_retrieval
    ports:
      - "9004:9004"
    volumes:
      - ./data:/data
      - model_cache:/root/.cache
    environment:
      - EMBED_MODEL=imagebind
      - INDEX_DIR=/data/faiss_index
      - DOCSTORE_PATH=/data/docstore.json
      - TOP_K=3
      - IN_DOCKER=true
    networks:
      - kittycash_cool_network

  generation_service:
    build:
      context: ./generation_service
    container_name: kittycash_generation
    ports:
      - "9005:9005"
    volumes:
      - ./data:/data
      - model_cache:/root/.cache
    environment:
      - LLM_MODEL=llama3:latest
      - TOP_K=3
      - IN_DOCKER=true
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - kittycash_cool_network

  mcp_server:
    build:
      context: ./mcp_server
    container_name: kittycash_mcp
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - retrieval_service
      - generation_service
      - data_indexing_service
    volumes:
      - ./data:/data
      - model_cache:/root/.cache
    environment:
      - RETRIEVAL_SERVICE_URL=http://retrieval_service:9004
      - GENERATION_SERVICE_URL=http://generation_service:9005
      - INDEXING_SERVICE_URL=http://data_indexing_service:9003
      - IN_DOCKER=true
    networks:
      - kittycash_cool_network

  api_server:
    build:
      context: ./api_service
    container_name: kittycash_api
    ports:
      - "9006:9006"
    depends_on:
      - mcp_server
    volumes:
      - ./data:/data
      - model_cache:/root/.cache
    environment:
      - MCP_SERVER_URL=http://mcp_server:9000/mcp
      - MCP_META_URL=http://mcp_server:9001
      - TOP_K=3
      - OLLAMA_ROUTER_MODEL=llama3:latest
      - KB_UPLOAD_DIR=/data
      - IN_DOCKER=true
    networks:
      - kittycash_cool_network

  kc_admin_service:
    build:
      context: ./kc_admin_service
    container_name: kc_admin_service
    ports:
      - "9009:9009"
    environment:
      - DATABASE_URL=postgresql://postgres:password@kittycash_db:5432/mydb
      - REDIS_URL=redis://kittycash_redis:6379/0
      - API_SERVER_URL=http://api_server:9006
    depends_on:
      - api_server 
    volumes:
      - ./kc_admin_service:/app
    restart: always
    networks:
      - kittycash_cool_network


networks:
  kittycash_cool_network:
    external: true

